name: tenthousandshotchallenge
version: 2.0.0+25
environment:
  sdk: ">=3.0.0 <4.0.0"
description: A flutter project for the Ten Thousand Shot Challenge app
dependencies:
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.3
  chewie: ^1.8.1
  cloud_firestore: ^5.6.9
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  data_connection_checker_nulls: ^0.0.2
  firebase_analytics: ^11.5.0
  firebase_auth: ^5.6.0
  firebase_core: ^3.14.0
  firebase_messaging: ^15.2.7
  firebase_remote_config: ^5.4.5
  firestore_cache: ^2.12.11
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.2
  flutter_datetime_picker_plus: ^2.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^19.3.0
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  global_configuration: ^2.0.0
  google_sign_in: ^6.3.0
  html: ^0.15.4
  http: ^1.2.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  introduction_screen: ^3.1.14
  mobile_scanner: ^7.0.1
  numberpicker: ^2.1.2
  package_info_plus: ^8.0.0
  password_strength: ^0.2.0
  permission_handler: ^12.0.0+1
  prompt_dialog: ^1.0.16
  provider: ^6.1.2
  pubspec_dependency_sorter: ^1.0.4
  purchases_flutter: ^8.10.3
  purchases_ui_flutter: ^8.10.4
  qr_flutter: ^4.1.0
  rotating_icon_button: ^1.0.0
  rxdart: ^0.28.0
  settings_ui: ^2.0.2
  share_plus: ^11.0.0
  shared_preferences: ^2.2.3
  sign_in_button: ^4.0.1
  sliding_up_panel: ^2.0.0+1
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.2.6
  vibration: ^3.1.3
  video_player: ^2.8.6
  word_generator: ^0.5.0
  youtube_player_flutter: ^9.0.1
dev_dependencies:
  build_runner: ^2.4.7
  fake_cloud_firestore: ^3.1.0
  firebase_auth_mocks: ^0.14.2
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
flutter_icons:
  android: launcher_icon
  image_path: assets/images/app-icon.png
  ios: true
flutter:
  assets:
    - assets/cfg/
    - assets/images/
    - assets/images/avatars/
    - assets/images/avatars/teams/
    - assets/images/avatars/players/
    - assets/images/avatars/characters/
    - assets/images/shop/
    - assets/fonts/
    - assets/animations/
  fonts:
    - family: NovecentoSans
      fonts:
        - asset: assets/fonts/novecento-sans-condensed-medium.otf
  uses-material-design: true
