name: tenthousandshotchallenge
version: 1.1.0+17
publish_to: none
description: A flutter project for the Ten Thousand Shot Challenge app
environment:
  sdk: ">=2.12.0 <4.0.0"
dependencies:
  auto_size_text: ^3.0.0
  auto_size_text_field: ^2.2.3
  chewie: ^1.8.1
  cloud_firestore: ^4.17.4
  connectivity_plus: ^6.0.3
  cupertino_icons: ^1.0.8
  data_connection_checker_nulls: ^0.0.2
  firebase_analytics: ^10.10.6
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_messaging: ^14.9.3
  firebase_remote_config: ^4.4.6
  firestore_cache: ^2.12.11
  fl_chart: ^0.68.0
  flutter_cache_manager: ^3.3.2
  flutter_datetime_picker_plus: ^2.2.0
  flutter_html: ^3.0.0-beta.2
  flutter_local_notifications: ^17.1.2
  flutter_svg: ^2.0.10+1
  fluttertoast: ^8.2.5
  font_awesome_flutter: ^10.7.0
  global_configuration: ^2.0.0
  google_sign_in: ^6.2.1
  html: ^0.15.4
  http: ^1.2.1
  intl: ^0.19.0
  introduction_screen: ^3.1.14
  numberpicker: ^2.1.2
  package_info: ^2.0.2
  password_strength: ^0.2.0
  prompt_dialog: ^1.0.16
  provider: ^6.1.2
  pubspec_dependency_sorter: ^1.0.4
  qr_flutter: ^4.1.0
  qrcode_barcode_scanner: ^3.0.1
  settings_ui: ^2.0.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  sign_in_button: ^3.2.0
  sliding_up_panel: ^2.0.0+1
  the_apple_sign_in: ^1.1.1
  url_launcher: ^6.2.6
  vibration: ^1.9.0
  video_player: 2.8.6
  word_generator: ^0.4.4
  youtube_player_flutter: ^9.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
flutter_icons:
  android: launcher_icon
  image_path: assets/images/app-icon.png
  ios: true
flutter:
  assets:
    - assets/cfg/
    - assets/images/
    - assets/images/avatars/
    - assets/images/avatars/teams/
    - assets/images/avatars/players/
    - assets/images/avatars/characters/
    - assets/images/shop/
    - assets/fonts/
    - assets/animations/
  fonts:
    - family: NovecentoSans
      fonts:
        - asset: assets/fonts/novecento-sans-condensed-medium.otf
  uses-material-design: true
