import 'package:flutter/material.dart' show BuildContext;
import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:tenthousandshotchallenge/models/firestore/Team.dart';

/// Data holder for one leaderboard row.
class LeaderboardPlayer {
  final String name;
  final int shots;
  const LeaderboardPlayer({required this.name, required this.shots});
}

/// Generates and shares/prints a team leaderboard PDF.
/// [team]    - the Team model (name, goal, dates)
/// [players] - sorted list (highest shots first)
Future<void> shareTeamLeaderboardPdf(
  BuildContext context,
  Team team,
  List<LeaderboardPlayer> players,
) async {
  final dateRange = '${DateFormat('MMM d, y').format(team.startDate ?? DateTime.now())} – '
      '${DateFormat('MMM d, y').format(team.targetDate ?? DateTime.now())}';
  final numberFmt = NumberFormat('#,###');
  final totalShots = players.fold<int>(0, (s, p) => s + p.shots);

  final doc = pw.Document();

  doc.addPage(
    pw.Page(
      pageFormat: PdfPageFormat.letter,
      margin: const pw.EdgeInsets.all(32),
      build: (pw.Context ctx) {
        return pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            // ── Header ─────────────────────────────────────────────────────
            pw.Text(
              (team.name ?? 'Team').toUpperCase(),
              style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'LEADERBOARD  ·  $dateRange',
              style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey700),
            ),
            pw.SizedBox(height: 4),
            pw.Text(
              'Team Total: ${numberFmt.format(totalShots)} shots'
              '${(team.goalTotal ?? 0) > 0 ? '  /  Goal: ${numberFmt.format(team.goalTotal)} shots' : ''}',
              style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold),
            ),
            pw.SizedBox(height: 16),
            pw.Divider(thickness: 1),
            pw.SizedBox(height: 8),

            // ── Table ───────────────────────────────────────────────────────
            pw.Table(
              columnWidths: {
                0: const pw.FixedColumnWidth(36), // Rank
                1: const pw.FlexColumnWidth(), // Name
                2: const pw.FixedColumnWidth(90), // Shots
                3: const pw.FixedColumnWidth(72), // % of goal
              },
              border: pw.TableBorder.all(color: PdfColors.grey300, width: 0.5),
              children: [
                // Header row
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    _cell('#', bold: true),
                    _cell('PLAYER', bold: true),
                    _cell('SHOTS', bold: true, alignRight: true),
                    _cell('% OF GOAL', bold: true, alignRight: true),
                  ],
                ),
                // Data rows
                for (int i = 0; i < players.length; i++)
                  pw.TableRow(
                    decoration: pw.BoxDecoration(
                      color: i % 2 == 0 ? PdfColors.white : PdfColors.grey50,
                    ),
                    children: [
                      _cell('${i + 1}', accent: i == 0),
                      _cell(players[i].name, accent: i == 0),
                      _cell(numberFmt.format(players[i].shots), alignRight: true, accent: i == 0),
                      _cell(
                        (team.goalTotal ?? 0) > 0 ? '${(players[i].shots / team.goalTotal! * 100).toStringAsFixed(1)}%' : '-',
                        alignRight: true,
                      ),
                    ],
                  ),
              ],
            ),
            pw.SizedBox(height: 16),
            pw.Divider(thickness: 0.5),
            pw.SizedBox(height: 4),
            pw.Text(
              'Generated by Ten Thousand Shot Challenge  ·  ${DateFormat('MMM d, y').format(DateTime.now())}',
              style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey500),
            ),
          ],
        );
      },
    ),
  );

  await Printing.sharePdf(
    bytes: await doc.save(),
    filename: '${(team.name ?? 'team').replaceAll(' ', '_')}_leaderboard.pdf',
  );
}

pw.Widget _cell(String text, {bool bold = false, bool alignRight = false, bool accent = false}) {
  return pw.Padding(
    padding: const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 5),
    child: pw.Text(
      text,
      textAlign: alignRight ? pw.TextAlign.right : pw.TextAlign.left,
      style: pw.TextStyle(
        fontSize: 11,
        fontWeight: bold || accent ? pw.FontWeight.bold : pw.FontWeight.normal,
        color: accent ? PdfColors.blue700 : PdfColors.black,
      ),
    ),
  );
}
